config/routes.rb
Rails.application.routes.draw do
  # top_page
  root 'shops#index'
  # author
  devise_for :authors, controllers: {
    sessions:      'authors/sessions',
    passwords:     'authors/passwords',
    registrations: 'authors/registrations'
  }
  resources :authors, only: [:show]
  get 'author/:id/shops/:shop_id' =>  'authors#shop_show', as: "shop_show"
  # author seat
  post 'shops/:id/seat/post' => 'seats#create', as: "post_seat"
  get 'shops/:id/seats' => 'seats#index', as: "seats"
  get 'shops/:id/seats/:seat_id' => 'authors#approval_seat' , as: "approval_seat"
  # chat
  mount ActionCable.server => '/cable'
  # user
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'rikuesuto'
      get 'quick'
      get 'favorite_shops'
      get :following, :followers
    end
  end
  # user follow
  resources :relationships, only: [:create, :destroy]
  # shop search
  get 'shops/search' => 'shops#search_station', as: "search_station"
  get 'shops/search/:search/genre/:id' => 'shops#search_station_genre', as: "search_station_genre"
  get 'shops/search_location' => 'shops#search_location', as: "search_location"
  get 'user_matching/shops' => 'users#search_matching_shop', as: "search_matching_shop"
  # shop
  resources :shops
  # shop review
  post 'shops/:id/review_create' => "shops#review_create", as: "shop_review_create"
  # author ßshop privilege
  post 'shops/:id/privilege/post' => "authors#privilege_create", as: "create_privilege"
  delete 'shops/:shop_id/privileges/:privilege_id' => "authors#privilege_destroy", as: "destroy_privilege"
  # shop prefecture search
  get 'shops/prefecture/:id' => 'shops#index_prefecture', as: "prefecture"
  # shop genre search
  get 'shops/genre/:id' => 'shops#index_genre', as: "genre"
  # shop fav
  get 'shops/fav/:id' => 'shops#fav', as: "fav_shops"
  # seat fav
  get 'seats/fav/:id' => 'seats#fav', as: "fav_seats"
  # author seat
  delete 'seats/:id' => 'seats#destroy', as: "seat_destroy"
  # user signout
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # notification
  get 'notifications', to: 'notifications#index'
  # shop fav_user
  get 'shops/:id/fav' => 'shops#shop_fav', as: "fav_user"
  # seat fav_user
  get 'seats/:id/fav' => 'seats#seat_like', as: "like_user"
  # seat user
  get 'shops/:id/user/seats' => 'seats#index_user', as: "seats_user"
  # user matching
  get 'users/:id/matching' => 'users#match', as: "match_user"
  # user quick
  get 'shops/:id/user/seat/:seat_id/quick' => 'seats#seat_reserve', as: "new_quick"
  post 'shops/:id/user/seat/:seat_id/quick/post' => 'seats#seat_reserve_create', as: "post_quick"
  delete 'quick/:quick_id' => 'seats#quick_delete', as: "quick_delete"
  # chat
  get 'users/:id/chat/:room_id' => 'users#chat', as: "user_chat"
  # user quick
  delete 'users/:id/request/destroy' => 'users#request_reject', as: "request_reject"
  patch 'users/:id/request/approval' => 'users#request_approval', as: "request_approval"
  get 'users/:id/quicks/:quick_id' => 'users#quick_show', as: "quick_show"
  get 'users/:id/requests/:request_id' => 'users#rikuesuto_show', as: "rikuesuto_show"
  # user location
  post 'location/post' => 'users#create_location', as: "location_create"
  # user imasugu
  get 'imasugu/shops' => 'seats#imasugu', as: "imasugu_shops"
end

app/models/seat.rb
class Seat < ApplicationRecord
  belongs_to :shop
  has_many :quicks, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  validates :time, presence: true
  validates :count, presence: true
  
  validate :check_seat_count

  # その予約が現在時間より後か
  scope :ok, -> { where("time >= ?", Time.now) }
  # その予約が埋まってるかどうか
  scope :fill, -> { where("fill = ?", false)}

  def check_seat_count
      if shop && shop.seats.count > 20
        errors.add(:shop, "に予約の登録は20件までです。削除して下さい。")
      end
  end

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  after_action :create_notifications, only: [:seat_reserve_create]
  before_action :authenticate_author!, only: [:create, :destroy, :index]
  # before_action :correct_author, only: [:index]
  before_action :authenticate_user!, only: [:index_user, :seat_like, :seat_reserve, :seat_reserve_create,
                                :quick_delete]


  def create
    @shop = Shop.find(params[:id])
    @seat = Seat.new(seat_params)
    @seat.shop_id = @shop.id
    if @seat.save
      redirect_to author_path(current_author.id)
    else
      @shop = Shop.find(params[:id])
      @seats = @shop.seats
      @seat_times = Array.new
      @seats.each do |seat|
      seat_time = seat.time.to_date
      @seat_times.push(seat_time)
      end
      @seat_times = @seat_times.uniq
      render "index"
    end
  end

  def destroy
    @seat = Seat.find(params[:id])
    @seat.destroy
    redirect_to author_path(current_author.id)
  end

  def index
    @shop = Shop.find(params[:id])
    @seat = Seat.new
    @seats = @shop.seats.order(time: "ASC")
    @seat_times = Array.new
    @seats.each do |seat|
      seat_time = seat.time.to_date
      @seat_times.push(seat_time)
    end
    @seat_times = @seat_times.uniq
  end

  def index_user
    @shop = Shop.find(params[:id])
    @seats = @shop.seats.fill.ok.order(time: "ASC")
    @seat_time = Array.new
    @seats.each do |seat|
      seat_t = seat.time.to_date
      @seat_time.push(seat_t)
    end
    @seat_time = @seat_time.uniq
  end

  def fav
    seat = Seat.find(params[:id])
    if seat.liked_by?(current_user)
      fav = current_user.likes.find_by(seat_id: seat.id)
      fav.destroy
      render json: seat.id
    else
      fav = current_user.likes.new(seat_id: seat.id)
      fav.save
      render json: seat.id
    end
  end

  def seat_like
    seat = Seat.find(params[:id])
    @users = seat.like_users.shuffle
  end

  def seat_reserve
    seat = Seat.find(params[:seat_id])
    @quick = Quick.new
  end

  def seat_reserve_create
    seat = Seat.find(params[:seat_id])
    shop = seat.shop
    @quick = Quick.new(user_id: current_user.id, friend_id: params[:quick][:friend_id], seat_id: seat.id)
    if seat.fill == true
      flash[:sign] = "もう埋まっています。"
      render 'seat_reserve'
    elsif @quick.save
      redirect_to quick_user_path(current_user.id)
    else 
      seat = Seat.find(params[:seat_id])
      render 'seat_reserve'
    end
  end

  def quick_delete
    @quick = Quick.find(params[:quick_id])
    @quick.destroy
    redirect_to quick_user_url(current_user.id)
  end

	def imasugu 
		latitude = params[:latitude].to_f
		longitude = params[:longitude].to_f
    @locations = Shop.within_box(0.310686, latitude, longitude)
		@seats = []
		for shop in @locations
			@seats.push(shop.seats.fill.where(time: Time.zone.now..Time.zone.now.since(2.hour)))
		end
    @seats = @seats.flatten
	end

  private

    def seat_params
      params.require(:seat).permit(:time, :count, :fill, :shop_id, :privilege_id, :privilege_secound_id, :privilege_third_id)
    end

    def create_notifications
        Notification.create(user_id: @quick.friend_id,
        notified_by_id: current_user.id,
        notified_type: 'リクエスト')
    end

    # def correct_author
    #   @author = Author.find(params[:id])
    #   redirect_to new_author_session_path unless @author = current_author
    # end
    
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/seats/_new.html.erb
<div class="new_modal" id="new<%= @date %>">
    <button class="close_new" id="<%= @date %>">close</button>
    <%= form_for @seat, url: post_seat_path do |f| %>
    <%= f.date_select :time, :default => @date %>
    <%= f.label :time, "時間"%>
    <%= f.time_select :time, :ignore_date => true, :default => Time.zone.now %><br>
    <%= f.label :count, "人数"%>
    <%= f.select :count, [["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"], ["6", "6"], ["7", "7"], ["8", "8"], ["9", "9"], ["10", "10"]]%><br>
    <%= f.label :privilege_id, "特典1"%>
    <%= f.collection_select :privilege_id, @shop.privileges, :id, :content, {:prompt => "Choose"} %><br>
    <%= f.label :privilege_id, "特典2"%>
    <%= f.collection_select :privilege_secound_id, @shop.privileges, :id, :content, {:prompt => "Choose"} %><br>
    <%= f.label :privilege_id, "特典3"%>
    <%= f.collection_select :privilege_third_id, @shop.privileges, :id, :content, {:prompt => "Choose"} %><br>
    <%= f.submit "save"%>
    <% end %>
</div>

app/views/seats/imasugu.html.erb
<%= stylesheet_link_tag "users/quick", :media => "all"%>
<%= render 'shared/iphone_menu'%>
<%= render 'shared/side_bar'%>

<table class="quick_table" style="width: 70%;">
 <tr>
  <th></th>
  <th>店名</th>
  <th>住所</th>
  <th>混雑</th>
  <th>時間</th>
 </tr>
<% @seats.each do |seat| %>
  <tr class="quick">
    <td>
      <%= attachment_image_tag seat.shop, :shop_image, :fill, 100, 100, fallback: "no_image.jpg"%>
    </td>
    <td>
      <%= link_to shop_path(seat.shop.id) do%>
      <%= seat.shop.shop_name%>
      <% end %>
    </td>
    <td>
      <%= seat.shop.prefecture.name%><%= seat.shop.address_city%><%= seat.shop.address_street%><%= seat.shop.address_street%>
    </td>
    <td>
      <%= seat.likes.count%>
    </td>
    <td>
    <%= link_to (seats_user_path(seat.shop.id)) do%>
      <%= seat.time.strftime("%d日%H時%M分") %>
    <% end %>
    </td>
  </tr>
<% end %>
</table>

app/views/seats/index.html.erb
<%= stylesheet_link_tag "users/seat", :media => "all"%>
<%= render 'shared/author_iphone_menu'%>

<% if @seat.errors.any? %>
  <div id="error_esplanation" class="alert alert-danger">
    <ul>
      <p style="font-size: 20px">You have
      <%= @seat.errors.full_messages.count %>errors.</p>
      <% @seat.errors.full_messages.each do |message|%>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= link_to (author_path(current_author.id)) do%>
  <button class="close">Back</button>
<% end %>

<div id="overlay"></div>

<h1>TavhU Events</h1>
  <%= month_calendar(attribute: :time, eventes: @seats) do |date, seats| %>
    <div class="calendar">
    <%= date.strftime("%Y年%m月%d日")%>
    </div>
    <div class="calendar_iphone">
    <%= date.strftime("%d日")%>
    </div>
    <div class="button">
      <button class="open_new" id="<%= date %>">登録</button>
      <% @date = date %>
      <%= render 'new'%>
    <% @seat_times.each do |seat|%>
    <% if seat == date%>
      <button class="open" id="<%= date %>">一覧</button>
      <button class="open_fill" id="<%= date %>">確定</button>
    <% end %>
    <% end %>
    </div>
  <% end %>

<% @seat_times.each do |seat_time| %>
<div id="modalWindow<%= seat_time %>" class="modal">
  <h3><%= seat_time.strftime("%Y年%m月%d日") %></h3>
  <button class="close" id="<%= seat_time %>">close</button>
  <table class="quick_table">
    <tr>
      <th>時間</th>
      <th>人数</th>
      <th>いいね数</th>
      <th>ステータス</th>
      <th>特典</th>
    </tr>
  <% @seats.where(fill: false).each do |seat| %>
    <tr class="quick">
    <% if seat.time.to_date == seat_time %>
      <td><%= seat.time.strftime("%H時%M分") %></td>
      <td><%= seat.count %>名様</td>
      <td><%= seat.likes.count %></td>
      <td>空席</td>
      <td>
        <%= link_to (seat_destroy_path(seat.id)), method: :delete do %>
          <button class="delete_btn">削除</button>
        <% end %>
      </td>
      <td>
        <ul>
        <% if seat.privilege_id.present? %>
          <li><%= Privilege.find(seat.privilege_id).content %></li>
        <% end %>
        <% if seat.privilege_secound_id.present? %>
          <li><%= Privilege.find(seat.privilege_secound_id).content %></li>
        <% end %>
        <% if seat.privilege_third_id.present? %>
          <li><%= Privilege.find(seat.privilege_third_id).content %></li>
        <% end %>
        </ul>
      </td>
      <% end %>
    </tr>
    <% end %>
  </table>
</div>
<% end %>



<% @seat_times.each do |seat_time| %>
<div id="fill<%= seat_time %>" class="modal">
  <h3><%= seat_time.strftime("%Y年%m月%d日") %></h3>
  <button class="close_fill" id="<%= seat_time %>">close</button>
  <table class="quick_table">
  <% @seats.where(fill: true).each do |seat| %>
    <tr class="quick">
    <% if seat.time.to_date == seat_time %>
      <td><%= seat.time.strftime("%H時%M分") %></td>
      <td><%= seat.count %>名様</td>
      <td><%= seat.likes.count %></td>
      <td>
        <%= link_to (approval_seat_path(id: @shop.id, seat_id: seat.id)) do %>
          <button class="show_btn">詳細</button>
        <% end %>
      </td>
      <% if seat.time < Time.zone.now %>
      <td>
        <%= link_to (seat_destroy_path(seat.id)), method: :delete do %>
          <button class="delete_btn">削除</button>
        <% end %>
      </td>
      <% end %>
      <td>
        <ul>
        <% if seat.privilege_id.present? %>
          <li><%= Privilege.find(seat.privilege_id).content %></li>
        <% end %>
        <% if seat.privilege_secound_id.present? %>
          <li><%= Privilege.find(seat.privilege_secound_id).content %></li>
        <% end %>
        <% if seat.privilege_third_id.present? %>
          <li><%= Privilege.find(seat.privilege_third_id).content %></li>
        <% end %>
        </ul>
      </td>
      <% end %>
    </tr>
    <% end %>
  </table>
</div>
<% end %>

app/views/seats/index_user.html.erb
<%= stylesheet_link_tag "users/seat", :media => "all" %>
<%= render 'shared/side_bar' %>
<%= render 'shared/iphone_menu'%>

<div id="overlay"></div>

<h1>TavhU Events</h1>
  <%= month_calendar(attribute: :time, events: @seats) do |date, seats| %>
    <div class="calendar">
    <%= date.strftime("%Y年%m月%d日") %>
    </div>
    <div class="calendar_iphone">
    <%= date.strftime("%d日")%>
    </div>
    <% @seat_time.each do |seat|%>
    <% if seat == date %>
      <button class="open" id="<%= date %>">open</button>
    <% end %>
    <% end %>
  <% end %>

<% @seat_time.each do |seat_t|%>
<div id="modalWindow<%= seat_t %>" class="modal">
  <h3><%= seat_t.strftime("%Y年%m月%d日") %></h3>
  <table class="quick_table">
    <tr class="quick">
      <th><button class="close" id="<%= seat_t %>">close</button></th>
    </tr>
  <% @seats.each do |seat| %>
    <tr class="quick">
    <% if seat.time.to_date == seat_t %>
      <td><%= seat.time.strftime("%H時%M分") %></td>
      <td><%= seat.count %>名様</td>
      <% if seat.fill == false %>
        <td>予約可</td>
        <td>
          <%= link_to (like_user_path(seat.id)) do %>
            <button class="favuser_btn">FavUser</button>
          <% end %>
        </td>
        <td>
          <%= link_to (new_quick_path(id: seat.shop.id, seat_id: seat.id)) do %>
            <button class="tavhu_btn">TabhU!!</button>
          <% end %>
        </td>
        <% if seat.liked_by?(current_user) %>
        <td>
          <%= link_to fav_seats_path(seat), class: "fav", remote: true do%>
            <i class="fa-thumbs-up" id="<%= seat.id %>"></i>
          <% end %>
        </td>
        <% else %>
        <td>
          <%= link_to fav_seats_path(seat), class: "fav", remote: true do%>
            <i class="far fa-thumbs-up" id="<%= seat.id %>"></i>
          <% end %>
        </td>
        <% end %>
      <% else %>
        <td>満席</td>
      <% end %>
        <td>
          <ul>
          <% if seat.privilege_id.present?%>
          <li><%= Privilege.find(seat.privilege_id).content %></li>
          <% end %>
          <% if seat.privilege_secound_id.present?%>
          <li><%= Privilege.find(seat.privilege_secound_id).content %></li>
          <% end %>
          <% if seat.privilege_third_id.present?%>
          <li><%= Privilege.find(seat.privilege_third_id).content %></li>
          <% end %>
          </ul>
        </td>
    <% end %>
    </tr>
  <% end %>
  </table>
</div>
<% end %>

app/views/seats/seat_like.html.erb
<%= stylesheet_link_tag "nomiya/members", :media => "all" %>
<%= render 'shared/iphone_menu'%>
<%= render 'shared/side_bar' %>
    <table class="users">
      <tr>
        <th> image </th><th> name </th>
      </tr>
    <% @users.each do |user| %>
    <tr class="user">
      <td class="user_image">
        <%= link_to (user_path(user.id)) do %>
        <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
        <% end %>
      </td>
      <td class="user_name">
        <%= user.name %>
      </td>
    </tr>
    <% end %>
    </table>

app/views/seats/seat_reserve.html.erb
<%= stylesheet_link_tag "form/reserve"%>
<%= render 'shared/iphone_menu'%>
<%= render 'shared/side_bar'%>

<% if @quick.errors.any?%>
  <div id="error_esplanation" class="alert alert-danger">
    <ul>
      <% @quick.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= flash[:sign] %>

<div class="select_form">
  <%= form_for @quick, url: post_quick_path do |f| %>
  <%= f.collection_select :friend_id, current_user.matchers, :id, :name, {:prompt => "Choose"}, {class: "form_user"} %>
  <div class="submit">
  <%= f.submit "save"%>
  </div>
<% end %>
<span class="form_user_highlight"></span>
<span class="form_user_selectbar"></span>
</div>