config/routes.rb
Rails.application.routes.draw do
  # top_page
  root 'shops#index'
  # author
  devise_for :authors, controllers: {
    sessions:      'authors/sessions',
    passwords:     'authors/passwords',
    registrations: 'authors/registrations'
  }
  resources :authors, only: [:show]
  get 'author/:id/shops/:shop_id' =>  'authors#shop_show', as: "shop_show"
  # author seat
  post 'shops/:id/seat/post' => 'seats#create', as: "post_seat"
  get 'shops/:id/seats' => 'seats#index', as: "seats"
  get 'shops/:id/seats/:seat_id' => 'authors#approval_seat' , as: "approval_seat"
  # chat
  mount ActionCable.server => '/cable'
  # user
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'rikuesuto'
      get 'quick'
      get 'favorite_shops'
      get :following, :followers
    end
  end
  # user follow
  resources :relationships, only: [:create, :destroy]
  # shop search
  get 'shops/search' => 'shops#search_station', as: "search_station"
  get 'shops/search/:search/genre/:id' => 'shops#search_station_genre', as: "search_station_genre"
  get 'shops/search_location' => 'shops#search_location', as: "search_location"
  get 'user_matching/shops' => 'users#search_matching_shop', as: "search_matching_shop"
  # shop
  resources :shops
  # shop review
  post 'shops/:id/review_create' => "shops#review_create", as: "shop_review_create"
  # author ßshop privilege
  post 'shops/:id/privilege/post' => "authors#privilege_create", as: "create_privilege"
  delete 'shops/:shop_id/privileges/:privilege_id' => "authors#privilege_destroy", as: "destroy_privilege"
  # shop prefecture search
  get 'shops/prefecture/:id' => 'shops#index_prefecture', as: "prefecture"
  # shop genre search
  get 'shops/genre/:id' => 'shops#index_genre', as: "genre"
  # shop fav
  get 'shops/fav/:id' => 'shops#fav', as: "fav_shops"
  # seat fav
  get 'seats/fav/:id' => 'seats#fav', as: "fav_seats"
  # author seat
  delete 'seats/:id' => 'seats#destroy', as: "seat_destroy"
  # user signout
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # notification
  get 'notifications', to: 'notifications#index'
  # shop fav_user
  get 'shops/:id/fav' => 'shops#shop_fav', as: "fav_user"
  # seat fav_user
  get 'seats/:id/fav' => 'seats#seat_like', as: "like_user"
  # seat user
  get 'shops/:id/user/seats' => 'seats#index_user', as: "seats_user"
  # user matching
  get 'users/:id/matching' => 'users#match', as: "match_user"
  # user quick
  get 'shops/:id/user/seat/:seat_id/quick' => 'seats#seat_reserve', as: "new_quick"
  post 'shops/:id/user/seat/:seat_id/quick/post' => 'seats#seat_reserve_create', as: "post_quick"
  delete 'quick/:quick_id' => 'seats#quick_delete', as: "quick_delete"
  # chat
  get 'users/:id/chat/:room_id' => 'users#chat', as: "user_chat"
  # user quick
  delete 'users/:id/request/destroy' => 'users#request_reject', as: "request_reject"
  patch 'users/:id/request/approval' => 'users#request_approval', as: "request_approval"
  get 'users/:id/quicks/:quick_id' => 'users#quick_show', as: "quick_show"
  get 'users/:id/requests/:request_id' => 'users#rikuesuto_show', as: "rikuesuto_show"
  # user location
  post 'location/post' => 'users#create_location', as: "location_create"
  # user imasugu
  get 'imasugu/shops' => 'seats#imasugu', as: "imasugu_shops"
end

app/models/shop.rb
class Shop < ApplicationRecord
	attachment :shop_image

	has_many :favorites, dependent: :destroy
	has_many :favorite_users, through: :favorites, source: :user
	has_many :seats, dependent: :destroy
	has_many :privileges, dependent: :destroy
	has_many :images, dependent: :destroy
	has_many :reviews, dependent: :destroy
	
	accepts_attachments_for :images, attachment: :image

	belongs_to :genre
	belongs_to :station
	belongs_to :author

	validates :shop_info, length: { maximum: 600 }
	validates :shop_name, presence: true
	validates :shop_info, presence: true
	validates :genre_id, presence: true
	validates :station_id, presence: true
	validates :address_city, presence: true
	validates :postcode, presence: true
	validates :prefecture_code, presence: true
	validates :address_street, presence: true 
	
	validate :check_shop_count

	geocoded_by :address
	after_validation :geocode, if: :address_changed?

	# 位置情報から範囲検索
	class << self
		def within_box(distance, latitude, longitude)
			distance = distance
			center_point = [latitude, longitude]
			box = Geocoder::Calculations.bounding_box(center_point, distance)
			self.within_bounding_box(box)
		end
	end

	def check_shop_count
		if author && author.shops.count > 5
			errors.add(:shop, "登録は5件までです。")
		end
	end


	include JpPrefecture
  jp_prefecture :prefecture_code
	
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end
  
  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

	def favorite_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	def self.search(search)
		if search
			joins(:station).includes(:station).where("stations.station_name LIKE ?", "%#{search}%")
		else
			all
		end
	end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
	before_action :authenticate_author!, only:[:new, :create, :destroy, :edit]
	before_action :authenticate_user!, only: [:index, :index_genre, :index_prefecture,
										:search_station, :search_station_genre, :search_location, :show,
										:shop_fav]

	def new
		@shop = Shop.new
		@shop.images.build
	end

	def create
		@shop = Shop.new(shop_params)
		@shop.address = @shop.address_city
		@shop.address = @shop.address.gsub(/\d+/, "").gsub(/\-+/, "")
		@shop.author_id = current_author.id
		@shop.genre_id = params[:shop][:genre_id]
		@shop.station_id = params[:shop][:station_id]
		@shop.save
		if @shop.save
			redirect_to author_path(current_author.id)
		else
			render "new"
		end
	end

	def edit
		@shop = Shop.find(params[:id])
	end

	def update
		@shop = Shop.find(params[:id])
		@shop.update(shop_params)
		if @shop.save
			redirect_to author_url(current_author)
		else
			render 'edit'
		end
	end

	def index
		@shops = Shop.find(Favorite.group(:shop_id).order('count(shop_id) desc').pluck(:shop_id))
		@shops = Kaminari.paginate_array(@shops).page(params[:page])
		@jp_prefectures = JpPrefecture::Prefecture.all
		@tohokus = Array.new
		@kantous = Array.new
		@tyubus = Array.new
		@kansais = Array.new
		@tyugokus = Array.new
		@sikokus = Array.new
		@kyusyus = Array.new
		for prefecture in @jp_prefectures
			if prefecture.area == "北海道"
				@tohokus.push(prefecture)
			elsif prefecture.area == "東北"
				@tohokus.push(prefecture)
			elsif prefecture.area == "関東"
				@kantous.push(prefecture)
			elsif prefecture.area == "中部"
				@tyubus.push(prefecture)
			elsif prefecture.area == "関西"
				@kansais.push(prefecture)
			elsif prefecture.area == "中国"
				@tyugokus.push(prefecture)
			elsif prefecture.area == "四国"
				@sikokus.push(prefecture)
			else
				@kyusyus.push(prefecture)
			end
		end
		@genres = Genre.all
	end

	def index_prefecture
		@shops = Shop.where(prefecture_code: params[:id]).page(params[:page])
	end

	def index_genre
		@shops = Shop.where(genre_id: params[:id]).page(params[:page])
	end

	def search_station
		@shops = Shop.search(params[:search]).page(params[:page])
	end

	def search_station_genre
		@shops = Shop.search(params[:search]).where(genre_id:params[:id]).page(params[:page])
	end

	def search_location
		latitude = params[:latitude].to_f
		longitude = params[:longitude].to_f
		@locations = Shop.within_box(0.310686, latitude, longitude).page(params[:page])
	end

	def show
		@shop = Shop.find(params[:id])
		@review = Review.new
		@reviews = @shop.reviews.order(created_at: "DESC")
		@average = @reviews.average(:star)
	end

	def review_create
		@review = Review.new(user_id: current_user.id, shop_id: params[:id], content: params[:review][:content], star: params[:review][:star])
		if @review.save
			redirect_to shop_url(params[:id])
		else
			@shop = Shop.find(params[:id])
			@reviews = @shop.reviews.order(created_at: "DESC")
			render 'show'
		end
	end

	def destroy
		@shop = Shop.find(params[:id])
		@shop.destroy
		redirect_to author_path(current_author.id)
	end

	def fav
		shop = Shop.find(params[:id])
		if shop.favorite_by?(current_user)
			fav = current_user.favorites.find_by(shop_id: shop.id)
			fav.destroy
			render json: shop.id
		else
			fav = current_user.favorites.new(shop_id: shop.id)
			fav.save
			render json: shop.id
		end
	end

	def shop_fav
		@shop = Shop.find(params[:id])
		@user = @shop.favorite_users.shuffle
	end

	private

		def shop_params
			params.require(:shop).permit(:shop_name, :shop_image, :shop_info, :genre_id, :station_id, :postcode, :prefecture_code, :address_city, :address_street, :address_building, images_images: [])
		end

end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_prefecture.html.erb
<ul class="nav">
<li><a class="iphone_ver">Home</a>
</li>
<li><a class="iphone_ver">Prefecture</a>
<ul>
<li><a>北海道,東北</a>
	<ul>
	<% @tohokus.each do |prefecture| %>
		<li><%= link_to (prefecture_path(id: prefecture.code)) do %><%= prefecture.name %><% end %></li>
	<% end %>
	</ul>
</li>
<li><a>関東</a>
	<ul>
	<% @kantous.each do |prefecture| %>
		<li><%= link_to (prefecture_path(id: prefecture.code)) do %><%= prefecture.name %><% end %></li>
	<% end %>
	</ul>
</li>
<li><a>中部</a>
	<ul>
	<% @tyubus.each do |prefecture| %>
		<li><%= link_to (prefecture_path(id: prefecture.code)) do %><%= prefecture.name %><% end %></li>
	<% end %>
	</ul>
</li>
<li><a>関西</a>
	<ul>
	<% @kansais.each do |prefecture| %>
		<li><%= link_to (prefecture_path(id: prefecture.code)) do %><%= prefecture.name %><% end %></li>
	<% end %>
	</ul>
</li>
<li><a>中国</a>
	<ul>
	<% @tyugokus.each do |prefecture| %>
		<li><%= link_to (prefecture_path(id: prefecture.code)) do %><%= prefecture.name %><% end %></li>
	<% end %>
	</ul>
</li>
<li><a>四国</a>
	<ul>
	<% @sikokus.each do |prefecture| %>
		<li><%= link_to (prefecture_path(id: prefecture.code)) do %><%= prefecture.name %><% end %></li>
	<% end %>
	</ul>
</li>
<li><a>九州</a>
	<ul>
	<% @kyusyus.each do |prefecture| %>
		<li><%= link_to (prefecture_path(id: prefecture.code)) do %><%= prefecture.name %><% end %></li>
	<% end %>
	</ul>
</li>
</ul>
</li>
<li><a class="iphone_ver">Genres</a>
<ul>
<% @genres.each do |genre| %>
<li><%= link_to (genre_path(id: genre.id)) do %><%= genre.genre_name %><% end %></li>
<% end %>
</ul>
</li>
<li><a class="iphone_ver">Stations</a>
<ul>
<li>
	<a>
		<%= form_tag(search_station_path, :method => 'get') do %>
			<%= text_field_tag :search %>
			<%= submit_tag 'Search', :station_name => nil %>
		<% end %>
	</a>
</li>
</ul>
</li>
<li><a class="iphone_ver">NearShops</a>
<ul>
<li>
	<a>
		<button class="find_btn" onclick="getPosition();">Find!!</button>
	</a>
</li>
</ul>
</li>
</ul>

<script>

    // 現在地取得処理
    function getPosition() {
      // 現在地を取得
      navigator.geolocation.getCurrentPosition(
        // 取得成功した場合
        function(position) {
            window.location.href = "/shops/search_location?latitude="+position.coords.latitude+"&longitude="+position.coords.longitude
            // $.ajax({
            //   url: "/shops/search_location",
            //   type: "GET",
            //   dataType: 'html',
            //   data: {latitude : position.coords.latitude,
            //         longitude : position.coords.longitude},
            // });
        },
        // 取得失敗した場合
        function(error) {
          switch(error.code) {
            case 1: //PERMISSION_DENIED
              alert("位置情報の利用が許可されていません");
              break;
            case 2: //POSITION_UNAVAILABLE
              alert("現在位置が取得できませんでした");
              break;
            case 3: //TIMEOUT
              alert("タイムアウトになりました");
              break;
            default:
              alert("その他のエラー(エラーコード:"+error.code+")");
              break;
          }
        }
      );
    }
  </script>
	<script>
    function getPositionquick() {
      navigator.geolocation.getCurrentPosition(
        function(position) {
            window.location.href = "/imasugu/shops?latitude="+position.coords.latitude+"&longitude="+position.coords.longitude
        },
        // 取得失敗した場合
        function(error) {
          switch(error.code) {
            case 1: //PERMISSION_DENIED
              alert("位置情報の利用が許可されていません");
              break;
            case 2: //POSITION_UNAVAILABLE
              alert("現在位置が取得できませんでした");
              break;
            case 3: //TIMEOUT
              alert("タイムアウトになりました");
              break;
            default:
              alert("その他のエラー(エラーコード:"+error.code+")");
              break;
          }
        }
      );
    }
	</script>

app/views/shops/_search_shops.html.erb
<div class="shop_all">
					<% @locations.each do |shop| %>
				<div class="shop_box">
					<div class="shop_head">
						<div class="shop_images">
						<div class="mainvisual">
							<div class="mainvisual-inner container">
								<div class="swiper-container">
									<div class="swiper-wrapper">
									<% if shop.shop_image.present?%>
										<div class="swiper-slide"><%= attachment_image_tag shop, :shop_image %></div>
									<% else %>
										<div class="swiper-slide"><%= image_tag '/images/no_image.jpg', class: "no_image"%></div>
									<% end %>
									<% if shop.images.present?%>
										<% shop.images.each do |image|%>
										<div class="swiper-slide"><%= attachment_image_tag image, :image %></div>
										<% end %>
									<% end %>
									</div><!-- .swiper-wrapper -->

									<div class="swiper-pagination"></div>
								
								</div><!-- .swiper-container -->
							</div><!-- .mainvisual-inner -->
						</div>
						<script>
								var swiper = new Swiper('.swiper-container', {
									effect: 'coverflow',
									grabCursor: true,
									centeredSlides: true,
									slidesPerView: 'auto',
									coverflowEffect: {
										rotate: 50,
										stretch: 0,
										depth: 100,
										modifier: 1,
										slideShadows : true,
									},
									pagination: {
										el: '.swiper-pagination',
									},
								});
							</script>
						</div>
						<div class="iphone_shop_name">
							<%= link_to (shop_path(shop.id)) do%>
								<%= shop.shop_name%>
							<% end %>
						</div>
						<div class="shop_name_station">
							<div class="shop_name">
							<%= link_to (shop_path(shop.id)) do %>
								<p><%= shop.shop_name %></p>
							<% end %>
							</div>
							<div class="station">
								<p>最寄駅： <%= shop.station.station_name %></p>
							</div>
							<div class="genre">
								<p>ジャンル： <%= shop.genre.genre_name %></p>
							</div>
							<div class="address">
								<p>〒<%= shop.postcode %> <%= shop.prefecture.name %><%= shop.address_city %><%= shop.address_street %></p>
							</div>
								<% if shop.favorite_by?(current_user) %>
										<%= link_to fav_shops_path(shop), class: "fav", remote: true do %>
										<i class="fa-thumbs-up" id="<%= shop.id %>"></i>
									<% end %>
										<%= shop.favorites.count%>
								<% else %>
										<%= link_to fav_shops_path(shop), class: "fav", remote: true do %>
										<i class="far fa-thumbs-up" id="<%= shop.id %>"></i>
									<% end %>
										<%= shop.favorites.count %>
								<% end %>
						</div>
					</div>
					<div class="shop_info">
				   <%= shop.shop_info %>
				  </div>
			  </div>
				<% end %>
		</div>

<%= paginate @locations%>

app/views/shops/_shop_all.html.erb
		<div class="shop_all">
					<% @shops.each do |shop| %>
				<div class="shop_box">
					<div class="shop_head">
						<div class="shop_images">
						<div class="mainvisual">
							<div class="mainvisual-inner container">
								<div class="swiper-container">
									<div class="swiper-wrapper">
									<% if shop.shop_image.present?%>
										<div class="swiper-slide"><%= attachment_image_tag shop, :shop_image %></div>
									<% else %>
										<div class="swiper-slide"><%= image_tag '/images/no_image.jpg', class: "no_image"%></div>
									<% end %>
									<% if shop.images.present?%>
										<% shop.images.each do |image|%>
										<div class="swiper-slide"><%= attachment_image_tag image, :image %></div>
										<% end %>
									<% end %>
									</div><!-- .swiper-wrapper -->

									<div class="swiper-pagination"></div>
								
								</div><!-- .swiper-container -->
							</div><!-- .mainvisual-inner -->
						</div>
						<script>
								var swiper = new Swiper('.swiper-container', {
									effect: 'coverflow',
									grabCursor: true,
									centeredSlides: true,
									slidesPerView: 'auto',
									coverflowEffect: {
										rotate: 50,
										stretch: 0,
										depth: 100,
										modifier: 1,
										slideShadows : true,
									},
									pagination: {
										el: '.swiper-pagination',
									},
								});
							</script>
						</div>
						<div class="iphone_shop_name">
						<%= link_to (shop_path(shop.id)), style: "text-decoration: none; color: rgb(82, 84, 86);" do%>
							<%= shop.shop_name%>
						<% end %>
						</div>
						<div class="shop_name_station">
							<div class="shop_name">
							<%= link_to (shop_path(shop.id)), style: "text-decoration: none; color: rgb(82, 84, 86);" do %>
								<p><%= shop.shop_name %></p>
							<% end %>
							</div>
							<div class="station">
								<p>最寄駅： <%= shop.station.station_name %></p>
							</div>
							<div class="genre">
								<p>ジャンル： <%= shop.genre.genre_name %></p>
							</div>
							<div class="address">
								<p>〒<%= shop.postcode %> <%= shop.prefecture.name %><%= shop.address_city %><%= shop.address_street %></p>
							</div>
								<% if shop.favorite_by?(current_user) %>
										<%= link_to fav_shops_path(shop), class: "fav", remote: true do %>
										<i class="fa-thumbs-up" id="<%= shop.id %>"></i>
									<% end %>
								<% else %>
										<%= link_to fav_shops_path(shop), class: "fav", remote: true do %>
										<i class="far fa-thumbs-up" id="<%= shop.id %>"></i>
									<% end %>
								<% end %>
						</div>
					</div>
					<div class="shop_info">
				   <%= shop.shop_info %>
				  </div>
			  </div>
				<% end %>
		</div>

<%= paginate @shops%>

app/views/shops/_shop_form.html.erb
<% if @shop.errors.any?%>
  <div id="error_esplanation" class="alert alert-danger">
    <ul>
      <p style="font-size: 20px;">You have
      <%= @shop.errors.full_messages.count %>errors.</p>
      <% @shop.errors.full_messages.each do |message|%>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="edit_form">
  <%= form_for(@shop) do |f|%>
    <%= render 'swiper'%>
    <div style="width: auto;">
    </div>
    <%= f.label :shop_image, "Image"%>
    <%= f.attachment_field :shop_image %>
    <%= f.attachment_field :images_images, multiple: true %>
    <%= f.attachment_field :images_images, multiple: true %>
    <%= f.attachment_field :images_images, multiple: true %>
    <%= f.attachment_field :images_images, multiple: true %>
    <%= f.attachment_field :images_images, multiple: true %>
    <%= f.attachment_field :images_images, multiple: true %>
    <%= f.attachment_field :images_images, multiple: true %>
    <%= f.label :shop_name, "Name"%>
    <%= f.text_field :shop_name %>
    <%= f.label :shop_info, "紹介"%>
    <%= f.text_area :shop_info %>
    <h3>Address</h3>
      <%= f.label :postcode, "Postcode"%>
      <%= f.number_field :postcode %>
      <%= f.label :prefecture_code, "都道府県"%><br>
      <%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name, include_blank: true  %><br>
      <%= f.label :address_city, "市町村"%>
      <%= f.text_field :address_city %>
      <%= f.label :address_street, "番地"%>
      <%= f.text_field :address_street %>
      <%= f.label :address_building, "建物"%>
      <%= f.text_field :address_building %>
      <%= f.label :genre_id, "Genre"%>
      <%= f.collection_select :genre_id, Genre.all, :id, :genre_name, {:prompt => "選択してください"} %><br>
      <%= f.label :station_id, "Station"%>
      <%= f.collection_select :station_id, Station.all, :id, :station_name, {:prompt => "選択してください"} %>
      <%= f.submit "Save" %>
  <% end %>
</div>

app/views/shops/_swiper.html.erb
<div class="mainvisual">
  <div class="mainvisual-inner container">
    <div class="swiper-container">
      <div class="swiper-wrapper">
        <div class="swiper-slide"><%= attachment_image_tag @shop, :shop_image,
          fallback: "no_image.jpg" %></div>
      <% if @shop.images.present?%>
        <% @shop.images.each do |image|%>
        <div class="swiper-slide"><%= attachment_image_tag image, :image %></div>
        <% end %>
      <% end %>
      </div><!-- .swiper-wrapper -->

      <div class="swiper-pagination"></div>

      <%# <div class="swiper-button-prev">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 27 44">
          <path class="arrow arrow-left" d="M0,22L22,0l2.1,2.1L4.2,22l19.9,19.9L22,44L0,22L0,22L0,22z" />
        </svg>
      </div><!-- .swiper-button-prev --> %>

      <%# <div class="swiper-button-next">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 27 44">
          <path class="arrow arrow-right" d="M27,22L27,22L5,44l-2.1-2.1L22.8,22L2.9,2.1L5,0L27,22L27,22z" />
        </svg>
      </div><!-- .swiper-button-next --> %>
    </div><!-- .swiper-container -->
  </div><!-- .mainvisual-inner -->
</div>
<script>
    var swiper = new Swiper('.swiper-container', {
      effect: 'coverflow',
      grabCursor: true,
      centeredSlides: true,
      slidesPerView: 'auto',
      coverflowEffect: {
        rotate: 50,
        stretch: 0,
        depth: 100,
        modifier: 1,
        slideShadows : true,
      },
      pagination: {
        el: '.swiper-pagination',
      },
    });
  </script>

app/views/shops/_top_swiper.html.erb
<div class="mainvisual">
  <div class="mainvisual-inner container">
    <div class="swiper-container">
      <div class="swiper-wrapper">
      <% if shop.shop_image.present?%>
        <div class="swiper-slide"><%= attachment_image_tag shop, :shop_image,
          fallback: "no_image.jpg" %></div>
      <% end %>
      <% if shop.images.present?%>
        <% shop.images.each do |image|%>
        <div class="swiper-slide"><%= attachment_image_tag image, :image %></div>
        <% end %>
      <% end %>
      </div><!-- .swiper-wrapper -->

      <div class="swiper-pagination"></div>

      <%# <div class="swiper-button-prev">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 27 44">
          <path class="arrow arrow-left" d="M0,22L22,0l2.1,2.1L4.2,22l19.9,19.9L22,44L0,22L0,22L0,22z" />
        </svg>
      </div><!-- .swiper-button-prev --> %>

      <%# <div class="swiper-button-next">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 27 44">
          <path class="arrow arrow-right" d="M27,22L27,22L5,44l-2.1-2.1L22.8,22L2.9,2.1L5,0L27,22L27,22z" />
        </svg>
      </div><!-- .swiper-button-next --> %>
    </div><!-- .swiper-container -->
  </div><!-- .mainvisual-inner -->
</div>
<script>
    var swiper = new Swiper('.swiper-container', {
      effect: 'coverflow',
      grabCursor: true,
      centeredSlides: true,
      slidesPerView: 'auto',
      coverflowEffect: {
        rotate: 50,
        stretch: 0,
        depth: 100,
        modifier: 1,
        slideShadows : true,
      },
      pagination: {
        el: '.swiper-pagination',
      },
    });
  </script>

app/views/shops/edit.html.erb
<%= stylesheet_link_tag "swiper"%>
<%= stylesheet_link_tag "form/edit", :media => "all"%>
<%= render 'shared/author_iphone_menu'%>
<%= render 'shop_form'%>
<style>
img {
  display: none;
}
</style>

app/views/shops/index_genre.html.erb
<%= stylesheet_link_tag "swiper"%>
<%= stylesheet_link_tag "nomiya/index", :media => "all"%>
<%= render 'shared/side_bar'%>
<%= render 'shared/iphone_menu'%>
<%= render 'shop_all'%>

app/views/shops/new.html.erb
<%= stylesheet_link_tag "swiper"%>
<%= stylesheet_link_tag "form/edit", :media => "all"%>
<%= render 'shared/author_iphone_menu'%>
<%= render 'shop_form'%>
<style>
img {
  display: none;
}
</style>

app/views/shops/search_location.html.erb
<%= stylesheet_link_tag "swiper"%>
<%= stylesheet_link_tag "nomiya/index", :media => "all"%>
<%= render 'shared/side_bar'%>
<%= render 'shared/iphone_menu'%>
<%= render 'search_shops'%>

app/views/shops/search_station.html.erb
<%= stylesheet_link_tag "swiper"%>
<%= stylesheet_link_tag "nomiya/index", :media => "all"%>
<%= render 'shared/side_bar'%>
<%= render 'shared/iphone_menu'%>
<ul class="nav_genre">
<li><a>Genres</a>
<ul>
<% Genre.all.each do |genre| %>
<li><%= link_to (search_station_genre_path(id: genre.id, search: params[:search])) do %><%= genre.genre_name %><% end %></li>
<% end %>
</ul>
</li>
</ul>
<%= render 'shop_all'%>

app/views/shops/search_station_genre.html.erb
<%= stylesheet_link_tag "swiper"%>
<%= stylesheet_link_tag "nomiya/index", :media => "all"%>
<%= render 'shared/side_bar'%>
<%= render 'shared/iphone_menu'%>
<%= render 'shop_all'%>

app/views/shops/shop_fav.html.erb
<%= stylesheet_link_tag "nomiya/members", :media => "all" %>
<%= render 'shared/side_bar' %>
<%= render 'shared/iphone_menu'%>
    <table class="users">
      <tr>
        <th> image </th><th> name </th>
      </tr>
    <% @user.each do |user| %>
    <tr class="user">
      <td class="user_image">
        <%= link_to (user_path(user.id)) do %>
        <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
        <% end %>
      </td>
      <td class="user_name">
        <%= user.name %>
      </td>
    </tr>
    <% end %>
    </table>