config/routes.rb
Rails.application.routes.draw do
  # top_page
  root 'shops#index'
  # author
  devise_for :authors, controllers: {
    sessions:      'authors/sessions',
    passwords:     'authors/passwords',
    registrations: 'authors/registrations'
  }
  resources :authors, only: [:show]
  get 'author/:id/shops/:shop_id' =>  'authors#shop_show', as: "shop_show"
  # author seat
  post 'shops/:id/seat/post' => 'seats#create', as: "post_seat"
  get 'shops/:id/seats' => 'seats#index', as: "seats"
  get 'shops/:id/seats/:seat_id' => 'authors#approval_seat' , as: "approval_seat"
  # chat
  mount ActionCable.server => '/cable'
  # user
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'rikuesuto'
      get 'quick'
      get 'favorite_shops'
      get :following, :followers
    end
  end
  # user follow
  resources :relationships, only: [:create, :destroy]
  # shop search
  get 'shops/search' => 'shops#search_station', as: "search_station"
  get 'shops/search/:search/genre/:id' => 'shops#search_station_genre', as: "search_station_genre"
  get 'shops/search_location' => 'shops#search_location', as: "search_location"
  get 'user_matching/shops' => 'users#search_matching_shop', as: "search_matching_shop"
  # shop
  resources :shops
  # shop review
  post 'shops/:id/review_create' => "shops#review_create", as: "shop_review_create"
  # author ßshop privilege
  post 'shops/:id/privilege/post' => "authors#privilege_create", as: "create_privilege"
  delete 'shops/:shop_id/privileges/:privilege_id' => "authors#privilege_destroy", as: "destroy_privilege"
  # shop prefecture search
  get 'shops/prefecture/:id' => 'shops#index_prefecture', as: "prefecture"
  # shop genre search
  get 'shops/genre/:id' => 'shops#index_genre', as: "genre"
  # shop fav
  get 'shops/fav/:id' => 'shops#fav', as: "fav_shops"
  # seat fav
  get 'seats/fav/:id' => 'seats#fav', as: "fav_seats"
  # author seat
  delete 'seats/:id' => 'seats#destroy', as: "seat_destroy"
  # user signout
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # notification
  get 'notifications', to: 'notifications#index'
  # shop fav_user
  get 'shops/:id/fav' => 'shops#shop_fav', as: "fav_user"
  # seat fav_user
  get 'seats/:id/fav' => 'seats#seat_like', as: "like_user"
  # seat user
  get 'shops/:id/user/seats' => 'seats#index_user', as: "seats_user"
  # user matching
  get 'users/:id/matching' => 'users#match', as: "match_user"
  # user quick
  get 'shops/:id/user/seat/:seat_id/quick' => 'seats#seat_reserve', as: "new_quick"
  post 'shops/:id/user/seat/:seat_id/quick/post' => 'seats#seat_reserve_create', as: "post_quick"
  delete 'quick/:quick_id' => 'seats#quick_delete', as: "quick_delete"
  # chat
  get 'users/:id/chat/:room_id' => 'users#chat', as: "user_chat"
  # user quick
  delete 'users/:id/request/destroy' => 'users#request_reject', as: "request_reject"
  patch 'users/:id/request/approval' => 'users#request_approval', as: "request_approval"
  get 'users/:id/quicks/:quick_id' => 'users#quick_show', as: "quick_show"
  get 'users/:id/requests/:request_id' => 'users#rikuesuto_show', as: "rikuesuto_show"
  # user location
  post 'location/post' => 'users#create_location', as: "location_create"
  # user imasugu
  get 'imasugu/shops' => 'seats#imasugu', as: "imasugu_shops"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :favorites, dependent: :destroy
  has_many :shops, through: :favorites
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :quicks, dependent: :destroy
  #follow
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  has_many :notifications, dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key:
  "follower_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :following, through: :active_relationships
  #phone_number
  VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
  validates :phone_number, presence: true, format: { with: VALID_PHONE_REGEX }
  validates :email, presence: true
  validates :introduce, presence: true, length: { maximum: 300 }
  validates :name, presence: true, length: { maximum: 20}
  #photo
  has_many :photos, dependent: :destroy
  accepts_attachments_for :photos, attachment: :photo

  #chat
  has_many :from_messages, class_name: "Message",
            foreign_key: "from_id", dependent: :destroy
  has_many :to_messages, class_name: "Message",
            foreign_key: "to_id", dependent: :destroy
  has_many :sent_messages, through: :from_messages, source: :from
  has_many :received_messages, through: :to_messages, source: :to

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def matchers
    User.where(id: passive_relationships.select(:follower_id)).where(id: active_relationships.select(:following_id))
  end

  # send dm
  def send_message(other_user, room_id, content)
    from_messages.create!(to_id: other_user.id, room_id: room_id, content: content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:rikuesuto, :rikuesuto_show, :request_reject, :request_approval,
                          :quick, :edit, :update,
                          :following, :followers]
  after_action :create_notifications, only: [:request_approval]
  helper_method :message_room_id
  before_action :chat_before, only: [:chat]
  protect_from_forgery :except => [:create_location]



  def show
  	@user = User.find(params[:id])
    @relationship = Relationship.new
    @room_id = message_room_id(current_user, @user)
    @messages = Message.recent_in_room(@room_id)
  end

  def rikuesuto
    @user = User.find(params[:id])
    @quicks = Quick.where(friend_id: @user.id).joins(:seat).includes(:seat).order("seats.time asc")
  end

  def rikuesuto_show
    @quick = Quick.find(params[:request_id])
  end

  def request_reject
    @user = User.find(params[:user_id])
    @quick = Quick.find(params[:quick_id])
    @quick.destroy
    redirect_to rikuesuto_user_path(@user.id)
  end

  def request_approval
    @user = User.find(params[:user_id])
    @quick = Quick.find(params[:quick_id])
    @seat = @quick.seat
    if @seat.fill == true
      @quick.destroy
      flash[:sign] = "このご予約はすでに埋まっています。"
      redirect_to rikuesuto_user_path(@user.id)
    else 
      @quick.request = true
      @quick.save
      @seat.fill = true
      @seat.save
      redirect_to rikuesuto_user_path(@user.id)
    end
  end

  def favorite_shops
    @shops = current_user.shops.page(params[:page])
  end

  def quick
    @user = User.find(params[:id])
    @quicks = Quick.where(user_id: @user.id).joins(:seat).includes(:seat).order("seats.time asc")
  end

  def quick_show
    @quick = Quick.find(params[:quick_id])
  end


  def chat
    @user = User.find(params[:id])
    @room_id = message_room_id(current_user, @user)
    @messages = Message.recent_in_room(@room_id)
  end

  def chat_before
    session[:user_id] = current_user.id
  end

  def match
    @user = current_user
    @users = @user.matchers.order(created_at: :desc)
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	@user.update(user_params)
  	redirect_to user_path(@user.id)
  end

  def following
    @user = User.find(params[:id])
    @users = @user.followings.order(created_at: :desc)
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.order(created_at: :desc)
    render 'show_follower'
  end

  def create_location
    @user = current_user
    @user.latitude = params[:latitude].to_f
    @user.longitude = params[:longitude].to_f
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user }
        format.json { render json: @user, js: "alert('Success!')" }
      else
        redirect_to user_path(current_user.id)
      end
    end
  end

  def search_matching_shop
    @user = User.find(params[:id])
    latitude = (@user.latitude + current_user.latitude)/2
    longitude = (@user.longitude + current_user.longitude)/2
    @locations = Shop.within_box(0.310686, latitude, longitude).page(params[:page])
  end

  def message_room_id(first_user, second_user)
    first_id = first_user.id.to_i
    second_id = second_user.id.to_i
    if first_id < second_id
      "#{first_user.id}-#{second_user.id}"
    else
      "#{second_user.id}-#{first_user.id}"
    end
  end

  
  private

    def user_params
    	params.require(:user).permit(:name, :profile_image, :introduce, :phone_number, photos_photos: [])
    end

    def create_notifications
      Notification.create(user_id: @quick.user_id,
      notified_by_id: @user.id,
      notified_type: 'リクエストを承認')
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to shops_path unless @user == current_user
    end


end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id), remote: true) do |f| %>
 <div><%= f.hidden_field :following_id %></div>
 <%= f.submit "follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
 <div id="follow_form">
 <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
 <% else %>
    <%= render 'follow' %>
 <% end %>
 </div>
<% end %>

app/views/users/_swiper.html.erb
<div class="mainvisual">
  <div class="mainvisual-inner container">
    <div class="swiper-container">
      <div class="swiper-wrapper">
        <div class="swiper-slide">
          <%= attachment_image_tag @user, :profile_image, :fill, 300, 300, fallback: "noimage.png"%>
        </div>
            <% @user.photos.each do |photo|%>
        <div class="swiper-slide"><%= attachment_image_tag photo, :photo, :fill, 300, 300 %></div>
        <% end %>
      </div><!-- .swiper-wrapper -->

      <div class="swiper-pagination"></div>

      <%# <div class="swiper-button-prev">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 27 44">
          <path class="arrow arrow-left" d="M0,22L22,0l2.1,2.1L4.2,22l19.9,19.9L22,44L0,22L0,22L0,22z" />
        </svg>
      </div><!-- .swiper-button-prev --> %>

      <%# <div class="swiper-button-next">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 27 44">
          <path class="arrow arrow-right" d="M27,22L27,22L5,44l-2.1-2.1L22.8,22L2.9,2.1L5,0L27,22L27,22z" />
        </svg>
      </div><!-- .swiper-button-next --> %>
    </div><!-- .swiper-container -->
  </div><!-- .mainvisual-inner -->
</div>
<script>
    var swiper = new Swiper('.swiper-container', {
      effect: 'coverflow',
      grabCursor: true,
      centeredSlides: true,
      slidesPerView: 'auto',
      coverflowEffect: {
        rotate: 50,
        stretch: 0,
        depth: 100,
        modifier: 1,
        slideShadows : true,
      },
      pagination: {
        el: '.swiper-pagination',
      },
    });
  </script>

app/views/users/chat.html.erb
<%= stylesheet_link_tag "users/chat", :media => "all"%>
<%= render 'shared/iphone_menu'%>
<%= render 'shared/side_bar'%>

<div id="chat">
    <section class="message_box">
      <div id="messages">
        <%= render @messages %>
      </div>
    </section>
    <script type="text/javascript">
      var height = 0;
      $("div.message").each( function() {
        height += ($(this).height());
      });
      $('section.message_box').scrollTop(height);
    </script>
</div>
  <div class="message_form">
    <%= render 'messages/message_form',{from_user: current_user, to_user: @user, room_id: @room_id} %>
  </div>

app/views/users/edit.html.erb
<%= stylesheet_link_tag "swiper"%>
<%= stylesheet_link_tag "form/edit", :media => "all" %>
<%= render 'shared/iphone_menu'%>
<%= render 'shared/side_bar' %>

<div class="edit_form">
  <div class="edit">
    <%= form_for(@user) do |f| %>
      <p>Name</p>
      <%= f.text_field :name, autofocus: true %>
      <p>Introduce</p>
      <%= f.text_area :introduce%>
      <p>ProfileImage</p>
      <%= render "swiper"%>
      <%= f.attachment_field :profile_image %>
      <%= f.attachment_field :photos_photos, multiple: true%>
      <%= f.attachment_field :photos_photos, multiple: true%>
      <%= f.attachment_field :photos_photos, multiple: true%>
      <%= f.attachment_field :photos_photos, multiple: true%>
      <%= f.submit "Save", class: "save" %>
    <% end %>
  </div>
</div>
<style>
img {
  display: none;
}
</style>

app/views/users/favorite_shops.html.erb
<%= stylesheet_link_tag "users/quick", :media => "all"%>
<%= render 'shared/iphone_menu'%>
<%= render 'shared/side_bar'%>

<table class="quick_table" style="width: 70%;">
  <tr class="iphone_none">
    <th></th>
    <th>店名</th>
    <th>住所</th>
    <th>いいね数</th>
  </tr>
<% @shops.each do |shop|%>
  <tr class="quick">
    <td>
      <%= attachment_image_tag shop, :shop_image, :fill, 100, 100, fallback: "no_image.jpg" %>
    </td>
    <td>
      <%= link_to shop_path(shop.id), style: "text-decoration: none; color: rgb(82, 84, 86);" do%>
      <%= shop.shop_name %>
      <% end %>
    </td>
    <td>
      <%= shop.prefecture.name %><%= shop.address_city%><%= shop.address_street%><%= shop.address_building %>
    </td>
    <td>
      <%= shop.favorites.count %>
    </td>
  </tr>
<% end %>
</table>

app/views/users/match.html.erb
<%= stylesheet_link_tag "nomiya/members", :media => "all" %>
<%= render 'shared/side_bar/' %>
<%= render 'shared/iphone_menu'%>

<table class="users">
  <tr>
    <th> image </th><th> name </th>
  </tr>
<% @users.each do |user| %>
<tr class="user">
  <td class="user_image">
    <%= link_to (user_path(user.id)) do %>
    <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
    <% end %>
  </td>
  <td class="user_name">
    <%= user.name %>
  </td>
  <td>
    <% @room_id = message_room_id(current_user, user) %>
    <%= link_to (user_chat_path(id: user.id, room_id: @room_id )), class: "btn" do %>
      <i class="fab fa-facebook-messenger face" ></i>
    <% end %>
  </td>
  <% if current_user.longitude.present? and user.longitude.present?%>
  <td>
    <%= link_to (search_matching_shop_path(id: user.id)), class: "btn place" do %>
      <i class="fa fa-street-view"></i>
    <% end %>
  </td>
  <% end %>
</tr>
<% end %>
</table>

app/views/users/quick.html.erb
<%= stylesheet_link_tag "users/quick", :media => "all" %>
<%= render 'shared/side_bar' %>
<%= render 'shared/iphone_menu'%>

<table class="quick_table">
  <% @quicks.each do |quick| %>
  <tr class="quick">
    <td class="quick_shop">
      <%= quick.seat.shop.shop_name %>
    </td>
    <td class="today">
      <%= quick.seat.time.strftime("%m月%d日 %H時%M分") %>
    </td>
    <td>
      <%= User.find(quick.friend_id).name %>さんへのリクエスト。
    </td>
    <td>
    <% if quick.request == false %>
      承認されていません
    <% else %>
      <i class="fas fa-star" style="color: #ff0000;"></i>当日は楽しんでください！
    <% end %>
    </td>
    <td>
      <%= link_to (quick_show_path(id: current_user.id, quick_id: quick.id)) do%>
        <button class="show_btn">詳細</button>
      <% end %>
    </td>
    <% if quick.seat.time < Time.zone.now %>
    <td>
      <%= link_to (quick_delete_path(id: current_user.id, quick_id: quick.id)), method: :delete do %>
        <button class="delete_btn">削除</button>
      <% end %>
    </td>
    <% end %>
  </tr>
  <% end %>
</table>

app/views/users/rikuesuto.html.erb
<%= stylesheet_link_tag "users/quick", :media => "all" %>
<%= render 'shared/side_bar' %>
<%= render 'shared/iphone_menu'%>

<% if @quicks.count == 5%>
  <div id="error_esplanation" class="alert alert-danger">
    <ul>
      <li>リクエストを削除しなければ、これ以上リクエストを受け付ける事ができません。</li>
    </ul>
  </div>
<% end %>
<% if flash[:sign].present?%>
  <div id="error_esplanation" class="alert alert-danger">
    <ul>
      <li><%= flash[:sign] %></li>
    </ul>
  </div>
<% end %>
<table class="quick_table">
  <% @quicks.each do |quick| %>
  <tr class="quick">
    <td class="quick_shop">
      <%= quick.seat.shop.shop_name %>
    </td>
    <td class="today">
      <%= quick.seat.time.strftime("%m月%d日 %H時%M分") %>
    </td>
    <td>
      <%= User.find(quick.user_id).name %>さんからお誘いが来ています。
    </td>
      <% if quick.request == false %>
      <td>
        <%= link_to (request_approval_path(user_id: current_user.id, quick_id: quick.id)), method: :patch do%>
          <button class="approval_btn">承認</button>
        <% end %>
      </td>
      <td>
        <%= link_to (request_reject_path(user_id: current_user.id, quick_id: quick.id)), method: :delete do%>
          <button class="delete_btn">拒否</button>
        <% end %>
      </td>
      <% else %>
      <td>
       <i class="fas fa-star" style="color: #ff0000;"></i>
      </td>
      <% if quick.seat.time < Time.zone.now %>
      <td>
        <%= link_to (request_reject_path(user_id: current_user.id, quick_id: quick.id)), method: :delete do%>
          <button class="delete_btn">削除</button>
        <% end %>
      </td>
      <% end %>
      <% end %>
    <td>
      <%= link_to (rikuesuto_show_path(id: current_user.id, request_id: quick.id)) do %>
        <button class="show_btn">詳細</button>
      <% end %>
    </td>
  </tr>
  <% end %>
  </table>

app/views/users/rikuesuto_show.html.erb
<%= stylesheet_link_tag "users/quick_show", :media => "all" %>
<%= render 'shared/side_bar' %>
<%= render 'shared/iphone_menu'%>

<table class="shop_table">
  <tbody>
    <tr>
      <th>一緒に行く人</th>
      <td><%= User.find(@quick.user_id).name %></td>
    </tr>
    <tr>
      <th>店名</th>
      <td>
        <%= link_to (shop_path(@quick.seat.shop.id)) do %>
          <%= @quick.seat.shop.shop_name %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th>住所</th>
      <td>〒<%= @quick.seat.shop.postcode %> <%=@quick.seat.shop.address_city %><%= @quick.seat.shop.address_street %><%= @quick.seat.shop.address_building %></td>
    </tr>
    <tr>
      <th>最寄駅</th>
      <td><%= @quick.seat.shop.station.station_name %></td>
    </tr>
    <tr>
      <th>時間</th>
      <td><%= @quick.seat.time.strftime("%Y年%m月%d日 %H時%M分") %></td>
    </tr>
    <tr>
      <th>特典</th>
      <td>
        <ul>
        <% if @quick.seat.privilege_id.present? %>
          <li><%= Privilege.find(@quick.seat.privilege_id).content %></li>
        <% end %>
        <% if @quick.seat.privilege_secound_id.present? %>
          <li><%= Privilege.find(@quick.seat.privilege_secound_id).content %></li>
        <% end %>
        <% if @quick.seat.privilege_third_id.present? %>
          <li><%= Privilege.find(@quick.seat.privilege_third_id).content %></li>
        <% end %>
        </ul>
    </td>
    </tr>
  </tbody>
</table>

app/views/users/search_matching_shop.html.erb
<%= stylesheet_link_tag "swiper"%>
<%= stylesheet_link_tag "nomiya/index", :media => "all"%>
<%= render 'shared/side_bar'%>
<%= render 'shared/iphone_menu'%>

<%= render 'shops/search_shops'%>

app/views/users/show.html.erb
<%= stylesheet_link_tag "swiper"%>
<%= stylesheet_link_tag "users/show", :media => "all" %>
<%= render 'shared/side_bar' %>
<%= render 'shared/iphone_menu'%>


<div class="profile">
  <div class="profile_image">
    <%= render 'swiper'%>
  </div>
  <div class="profile_info">
    <div class="edit">
      <div class="name">
        <%= @user.name %>
      </div>
      <%= render 'follow_form' %>
      <% if @user.id == current_user.id %>
      <div class="editandmatching">
        <div class="editbutton">
          <%= link_to (edit_user_path(@user)), class: "btn" do %>
          <i class="fa fa-edit"></i>
          <% end %>
        </div>
        <button class="btn place" onclick="getPosition();"><i class="fa fa-map-pin"></i></button>
        <div style="float: right">
          <%= link_to (favorite_shops_user_path(@user)), class: "btn shop" do%>
            <i class="fa fa-star"></i>
          <% end %>
        </div>
        <div class="matching">
          <%= link_to (match_user_path(@user)), class: "btn match" do %>
          <i class="fa fa-users"></i>
          <% end %>
        </div>
      <%= render 'stats' %>
      </div>
      <% end %>
      <div class="introduction">
        <p><%= @user.introduce %></p>
      </div>
    </div>
  </div>
</div>

<% if @user.id == current_user.id%>
<script>
    if (navigator.geolocation) {
      alert("この端末では位置情報が取得できます");
    } else {
      alert("この端末では位置情報が取得できません");
    }

    function getPosition() {
      navigator.geolocation.getCurrentPosition(
        function(position) {
            alert("Success!");
            $.ajax({
              url: "/location/post",
              type: "POST",
              data: {latitude : position.coords.latitude,
                    longitude : position.coords.longitude},
              dataType: 'json'
            });
        },
        function(error) {
          switch(error.code) {
            case 1: //PERMISSION_DENIED
              alert("位置情報の利用が許可されていません");
              break;
            case 2: //POSITION_UNAVAILABLE
              alert("現在位置が取得できませんでした");
              break;
            case 3: //TIMEOUT
              alert("タイムアウトになりました");
              break;
            default:
              alert("その他のエラー(エラーコード:"+error.code+")");
              break;
          }
        }
      );
    }
</script>
<% end %>

app/views/users/show_follow.html.erb
<%= stylesheet_link_tag "nomiya/members", :media => "all" %>
<%= render 'shared/side_bar' %>
<%= render 'shared/iphone_menu'%>
    <table class="users">
      <tr>
        <th> image </th><th> name </th>
      </tr>
    <% @user.followings.each do |user| %>
      <tr class="user">
        <td class="user_image">
          <%= link_to (user_path(user.id)) do %>
          <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
          <% end %>
        </td>
        <td class="user_name">
          <%= user.name %>
        </td>
      <tr>
    <% end %>
    </table>

app/views/users/show_follower.html.erb
<%= stylesheet_link_tag "nomiya/members", :media => "all" %>
<%= render 'shared/side_bar' %>
<%= render 'shared/iphone_menu'%>

<table class="users">
  <tr>
    <th> image </th><th> name </th>
  </tr>
<% @user.followers.each do |user| %>
<tr class="user">
  <td class="user_image">
    <%= link_to (user_path(user.id)) do %>
    <%= attachment_image_tag user, :profile_image, :fill, 100, 100,fallback: "no_image.jpg" %>
    <% end %>
  </td>
  <td class="user_name">
    <%= user.name %>
  </td>
</tr>
<% end %>
</table>