config/routes.rb
Rails.application.routes.draw do
  # top_page
  root 'shops#index'
  # author
  devise_for :authors, controllers: {
    sessions:      'authors/sessions',
    passwords:     'authors/passwords',
    registrations: 'authors/registrations'
  }
  resources :authors, only: [:show]
  get 'author/:id/shops/:shop_id' =>  'authors#shop_show', as: "shop_show"
  # author seat
  post 'shops/:id/seat/post' => 'seats#create', as: "post_seat"
  get 'shops/:id/seats' => 'seats#index', as: "seats"
  get 'shops/:id/seats/:seat_id' => 'authors#approval_seat' , as: "approval_seat"
  # chat
  mount ActionCable.server => '/cable'
  # user
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'rikuesuto'
      get 'quick'
      get 'favorite_shops'
      get :following, :followers
    end
  end
  # user follow
  resources :relationships, only: [:create, :destroy]
  # shop search
  get 'shops/search' => 'shops#search_station', as: "search_station"
  get 'shops/search/:search/genre/:id' => 'shops#search_station_genre', as: "search_station_genre"
  get 'shops/search_location' => 'shops#search_location', as: "search_location"
  get 'user_matching/shops' => 'users#search_matching_shop', as: "search_matching_shop"
  # shop
  resources :shops
  # shop review
  post 'shops/:id/review_create' => "shops#review_create", as: "shop_review_create"
  # author ßshop privilege
  post 'shops/:id/privilege/post' => "authors#privilege_create", as: "create_privilege"
  delete 'shops/:shop_id/privileges/:privilege_id' => "authors#privilege_destroy", as: "destroy_privilege"
  # shop prefecture search
  get 'shops/prefecture/:id' => 'shops#index_prefecture', as: "prefecture"
  # shop genre search
  get 'shops/genre/:id' => 'shops#index_genre', as: "genre"
  # shop fav
  get 'shops/fav/:id' => 'shops#fav', as: "fav_shops"
  # seat fav
  get 'seats/fav/:id' => 'seats#fav', as: "fav_seats"
  # author seat
  delete 'seats/:id' => 'seats#destroy', as: "seat_destroy"
  # user signout
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # notification
  get 'notifications', to: 'notifications#index'
  # shop fav_user
  get 'shops/:id/fav' => 'shops#shop_fav', as: "fav_user"
  # seat fav_user
  get 'seats/:id/fav' => 'seats#seat_like', as: "like_user"
  # seat user
  get 'shops/:id/user/seats' => 'seats#index_user', as: "seats_user"
  # user matching
  get 'users/:id/matching' => 'users#match', as: "match_user"
  # user quick
  get 'shops/:id/user/seat/:seat_id/quick' => 'seats#seat_reserve', as: "new_quick"
  post 'shops/:id/user/seat/:seat_id/quick/post' => 'seats#seat_reserve_create', as: "post_quick"
  delete 'quick/:quick_id' => 'seats#quick_delete', as: "quick_delete"
  # chat
  get 'users/:id/chat/:room_id' => 'users#chat', as: "user_chat"
  # user quick
  delete 'users/:id/request/destroy' => 'users#request_reject', as: "request_reject"
  patch 'users/:id/request/approval' => 'users#request_approval', as: "request_approval"
  get 'users/:id/quicks/:quick_id' => 'users#quick_show', as: "quick_show"
  get 'users/:id/requests/:request_id' => 'users#rikuesuto_show', as: "rikuesuto_show"
  # user location
  post 'location/post' => 'users#create_location', as: "location_create"
  # user imasugu
  get 'imasugu/shops' => 'seats#imasugu', as: "imasugu_shops"
end

app/views/shared/_author_iphone_menu.html.erb
<nav class="iphone_nav">
  <div class="drawer">
    <%= image_tag "/images/logo_transparent.png", :size => '80x80'%>
  <div class="navbar_toggle">
    <span class="navbar_toggle_icon"></span>
    <span class="navbar_toggle_icon"></span>
    <span class="navbar_toggle_icon"></span>
  </div>
  </div>
  <div class="menu">
  <ul style="list-style: none;">
    <li><%= current_author.email %>さんこんにちは</li>
    <li><%= link_to "MYPAGE", author_path(current_author) %></li>
    <li><%= link_to "NEWSHOP", new_shop_path %></li>
    <li><%= link_to "Loagout", destroy_author_session_path, method: :delete %></li>
  </ul>
  </div>
</nav>
<script>
$(function() {
  $('.navbar_toggle').on('click', function () {
    $(this).toggleClass('open_iphone');
    $('.menu').toggleClass('open_iphone');
  });
});
</script>

app/views/shared/_iphone_menu.html.erb
<nav class="iphone_nav">
 <div class="drawer">
    <%= image_tag "/images/logo_transparent.png", :size => '80x80'%>
  	<%= render 'notifications/notification_dropdown' %>
  <div class="navbar_toggle">
   <span class="navbar_toggle_icon"></span>
   <span class="navbar_toggle_icon"></span>
   <span class="navbar_toggle_icon"></span>
  </div>
 </div>
 <div class="menu">
  <ul style="list-style: none;">
	 <li><%= link_to "MYPAGE", user_path(current_user) %></li>
   <li><%= link_to "TAVERN", shops_path %></li>
   <li><%= link_to "REQUEST", rikuesuto_user_path(current_user.id) %></li>
   <li><%= link_to "QUICK", quick_user_path(current_user.id) %></li>
   <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
  </ul>
 </div>
</nav>
<script>
$(function() {
 $('.navbar_toggle').on('click', function () {
  $(this).toggleClass('open_iphone');
  $('.menu').toggleClass('open_iphone');
 });
});
</script>

app/views/shared/_side_bar.html.erb
<div id="MenuIcon">
  <div id="MenuLine"></div>
</div>
<div id="MainMenu">
  <div id="logo">
    <%= image_tag "/images/logo_transparent.png", :size => '150x150'%>
  </div>
  <nav>
  	<%= render 'notifications/notification_dropdown' %>
  </nav>

  <ul class="abc">
    <li>HOME<div class="line"></div></li>
    <li><%= link_to "MyProfile", user_path(current_user.id), style: "text-decoration: none; color: white;"  %><div class="line"></div></li>
        <li><%= link_to "TAVERN", shops_path, style: "text-decoration: none; color: white;" %><div class="line"></div></li>
    <li><%= link_to "REQUEST", rikuesuto_user_path(current_user.id), style: "text-decoration: none; color: white;" %><div class="line"></div></li>
    <li><%= link_to "QUICK", quick_user_path(current_user.id), style: "text-decoration: none; color: white;" %><div class="line"></div></li>
    <li><%= link_to "Logout", destroy_user_session_path, method: :delete, style: "text-decoration: none; color: white;" %><div class="line"></div></li>
  </ul>

  <div id="close">
    <img src="/images/Close.png" alt="close" height="30px" width="30px"/>
  </div>
</div>